### ISSUE TITLE
[BUG] item duplicate

### ISSUE THREAD

**Issue by yoku0206** [1bacon/drops-into-shulker#4] opened 2023-08-01 03:16 UTC
If shulker box can stack, the item will duplicate

**Comment by yoku0206** [comment] 2023-08-01 03:19
By the way i try it use carpet stackableShulkerBoxes

**Comment by 1bacon** [comment] 2024-01-07 21:57
Sorry I totally missed this. 
Can you describe what you did exactly? I'm guessing you stack empty shulkers, then take them into the off-hand and collect items. Those are then in all the shulkers of the stack?

I'll test this and get back to you.

**Comment by 1bacon** [comment] 2024-01-07 22:07
So yeah, I just tested it and it does dupe the drops. I'm not quite sure what to do here. 
Either don't allow pickups with multiple shulkers or force the other shulkers out and redirect the drops into the one remaining.

I think not redirecting the items and displaying some type of message is the easiest way.

**Comment by 1bacon** [comment] 2024-01-07 23:12
This should be fixed with 3ead0cd. 

I'm closing this, but feel free to re-open when the problem is not fixed.

**Closed by 1bacon** 2024-01-07 23:12 UTC
